version: "3.3"

services:
  wordpress:
    image: docker.io/presslabs/wordpress-runtime:latest-wp-php-8.1
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    depends_on:
      - db
      - memcached
    volumes:
      - ./config:/app/config
      - ./wp-content:/app/web/wp-content:rw
      - ./.dev/wp-config-docker.php:/app/web/wp-config.php:rw
      - ./.dev/php.ini:/usr/local/etc/php/conf.d/zz-local.ini
    ports:
      - "8080:8080"
    restart: always
    tmpfs:
      - /usr/local/docker/etc:uid=${USER_ID:-1000},gid=${GROUP_ID:-1000}
      - /var/run:uid=${USER_ID:-1000},gid=${GROUP_ID:-1000}
    environment:
      WP_ENVIRONMENT_TYPE: development
      DB_HOST: db:3306
      DB_USER: wordpress
      DB_PASSWORD: not-so-secure
      DB_NAME: wordpress
      MEMCACHED_HOST: memcached:11211
      PHP_REQUEST_TIMEOUT: 300
      WORKER_GROUP: ${USER_ID:-1000}
      WORKER_USER: ${GROUP_ID:-1000}
      ## Proxy all missing media files from local to remote site for easy development.
      # MEDIA_FALLBACK_URL: https://<parent domain name>

  db:
    image: percona:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./.dev/my.cnf:/etc/my.cnf.d/my.cnf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: not-so-secure
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: not-so-secure

  memcached:
    image: memcached:1.6

volumes:
  db_data: {}
